# Generated by Django 3.1.1 on 2020-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_mind_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindpost',
            name='title',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mindpost',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
