# Generated by Django 3.1.1 on 2020-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_mind_app', '0002_auto_20201002_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindpost',
            name='title2',
            field=models.CharField(default='Пустой подзаголовок', max_length=64),
            preserve_default=False,
        ),
    ]
