# Generated by Django 3.1.1 on 2020-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_mind_app', '0004_remove_mindpost_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindpost',
            name='title2',
            field=models.CharField(default=True, max_length=64),
            preserve_default=False,
        ),
    ]
