# Generated by Django 3.1.1 on 2020-10-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('true_mind_app', '0005_mindpost_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindpost',
            name='title2',
        ),
    ]
